on: 
  push:
    branches: [ main ]
  release:
    types: [published]
name: Node.js CI Main
jobs:
  build:
    name: build and publish to docker hub
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        # node-version: ${{ matrix.node-version }}
        node-version: '14.16.0'
    - name: Install dependencies
      run: yarn install
    - name: Test
      run: npm test 
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: terminator1997/nodejs-cicd
          tag_with_ref: true