on: 
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
name: Node.js CI Develop
jobs:
  build:
    name: build and publish to docker hub
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        # node-version: ${{ matrix.node-version }}
        node-version: '14.16.0'
    - name: Install dependencies
      run: yarn install
    - name: Test
      run: npm test 